// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "49feb0eb-e3bc-449e-be75-464f12951708";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onGSRChange();
void onMAXChange();
void onMPUChange();

float GSR;
float MAX;
float MPU;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(GSR, READWRITE, ON_CHANGE, onGSRChange);
  ArduinoCloud.addProperty(MAX, READWRITE, ON_CHANGE, onMAXChange);
  ArduinoCloud.addProperty(MPU, READWRITE, ON_CHANGE, onMPUChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
