#include "arduino_secrets.h"
/* 
  Sketch generated by the Arduino IoT Cloud Thing "wristband"
  https://create.arduino.cc/cloud/things/f2d72524-5d60-485e-bb32-37d962cdb6ac 

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  float GSR;
  float MAX;
  float MPU;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/

#include "thingProperties.h"
#include <DFRobot_MAX30102.h>
#include "I2Cdev.h"
#include "MPU6050.h"
#include <WiFi.h>


#define SKIN_CONDUCTENCE_PIN A0
int sensorValue=0;
int gsr_average=0;
#if I2CDEV_IMPLEMENTATION == I2CDEV_ARDUINO_WIRE
    #include "Wire.h"
#endif
DFRobot_MAX30102 particleSensor;
MPU6050 accelgyro;

int16_t ax, ay, az;
int16_t gx, gy, gz;

#define OUTPUT_READABLE_ACCELGYRO
#define LED_PIN 13
bool blinkState = false;
void setup() {
  // Initialize serial and wait for port to open:
  Serial.begin(9600);
   pinMode(LED_PIN, OUTPUT);

  // Initialize Arduino Cloud variables
  initProperties();

 // Connect to Wi-Fi
  Serial.println();
  Serial.println();
  Serial.print("Connecting to ");
  Serial.println(SECRET_SSID);

  WiFi.begin(SECRET_SSID, SECRET_OPTIONAL_PASS);

  while (WiFi.status()!= WL_CONNECTED) {
    delay(500);
    Serial.print(".");
  }

  Serial.println("");
  Serial.println("WiFi connected");
  Serial.println("IP address: ");
  Serial.println(WiFi.localIP());

  // Initialize Arduino Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);

  // Connect to Arduino Cloud
  while (!ArduinoCloud.connected()) {
    Serial.print("Connecting to Arduino Cloud...");
    delay(1000);
  }
  // This delay gives the chance to wait for a Serial Monitor without blocking if none is found
  delay(1500); 

//Init serial

  Serial.println("Initializing I2C devices...");
    accelgyro.initialize();
 Serial.println("Testing device connections...");
    Serial.println(accelgyro.testConnection() ? "MPU6050 connection successful" : "MPU6050 connection failed");


  while (!particleSensor.begin()) {
    Serial.println("MAX30102 was not found");
    delay(1000);
  }
  particleSensor.sensorConfiguration(/*ledBrightness=*/50, /*sampleAverage=*/SAMPLEAVG_4, \
                        /*ledMode=*/MODE_MULTILED, /*sampleRate=*/SAMPLERATE_100, \
                        /*pulseWidth=*/PULSEWIDTH_411, /*adcRange=*/ADCRANGE_16384);

pinMode(LED_PIN, OUTPUT);
 
  
  /*
     The following function allows you to obtain more information
     related to the state of network and IoT Cloud connection and errors
     the higher number the more granular information you’ll get.
     The default is 0 (only errors).
     Maximum is 4
 */
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();
}

int32_t SPO2; //SPO2
int8_t SPO2Valid; //Flag to display if SPO2 calculation is valid
int32_t heartRate; //Heart-rate
int8_t heartRateValid; //Flag to display if heart-rate calculation is valid 


void loop() {
  ArduinoCloud.update();
  // Your code here 
  Serial.println(F("Wait about four seconds"));
  particleSensor.heartrateAndOxygenSaturation(/**SPO2=*/&SPO2, /**SPO2Valid=*/&SPO2Valid, /**heartRate=*/&heartRate, /**heartRateValid=*/&heartRateValid);
  //Print result 
  Serial.print(F("heartRate="));
  Serial.print(heartRate, DEC);
  Serial.print(F(", heartRateValid="));
  Serial.print(heartRateValid, DEC);
  Serial.print(F("; SPO2="));
  Serial.print(SPO2, DEC);
  Serial.print(F(", SPO2Valid="));
  Serial.println(SPO2Valid, DEC);

  // read raw accel/gyro measurements from device
    accelgyro.getMotion6(&ax, &ay, &az, &gx, &gy, &gz);

    // these methods (and a few others) are also available
    //accelgyro.getAcceleration(&ax, &ay, &az);
    //accelgyro.getRotation(&gx, &gy, &gz);

    #ifdef OUTPUT_READABLE_ACCELGYRO
        // display tab-separated accel/gyro x/y/z values
        Serial.print("a/g:\t");
        Serial.print(ax); Serial.print("\t");
        Serial.print(ay); Serial.print("\t");
        Serial.print(az); Serial.print("\t");
        Serial.print(gx); Serial.print("\t");
        Serial.print(gy); Serial.print("\t");
        Serial.println(gz);
    #endif

      blinkState = !blinkState;
    digitalWrite(LED_PIN, blinkState);




  long sum=0;
  for(int i=0;i<10;i++)           //Average the 10 measurements to remove the glitch
      {
      sensorValue=analogRead(SKIN_CONDUCTENCE_PIN);
      sum += sensorValue;
      delay(5);
      }
   gsr_average = sum/10;
   Serial.println(gsr_average);

 // send data to cloud
  GSR=gsr_average;
  MAX=heartRate;
  MPU=avg(ax,ay,az);


}


float avg(int x, int y, int z){
    return (x+y+z)/3;
}

/*
  Since GSR is READ_WRITE variable, onGSRChange() is
  executed every time a new value is received from IoT Cloud.
*/

void onGSRChange()  {
  // Add your code here to act upon GSR change
}
/*
  Since MAX is READ_WRITE variable, onMAXChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onMAXChange()  {
  // Add your code here to act upon MAX change
}
/*
  Since MPU is READ_WRITE variable, onMPUChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onMPUChange()  {
  // Add your code here to act upon MPU change
}